### ISSUE TITLE
Entity display precision not used by charger card?

### ISSUE THREAD

**Issue by newlund** [tmjo/charger-card#46]
Hi!

It seems entity display precision is not used by charger card? Or maybe I have something misconfigured causing the insane number of decimals? :)

![image](https://user-images.githubusercontent.com/1943085/231688256-c0fa44d1-7121-401f-b986-c8743ed4ef5e.png)

BR/Nicklas

**Comment by tmjo** [comment]
Hmm, that looks rather insane :) I've never seen this happen, so I am not sure what is causing it. Is it the entities from Easee integration that is in use here?

Please let me know HA version and version of Easee integration as well. The Easee integration was updated yesterday, and I haven't tested that. It may be that precision was removed from the integration since HA now supports it in core, so I can check that.

Could you also verify what precision is selected for a couple of those crazy numbers?

**Comment by newlund** [comment]
The Easee integration is v,0.9.49 (and HA 2023.4.3). Updated today
Probably caused by the newer version as you wrote.
The precision is set to default on all of them. For session energy it is 15.3 ( 1 decimal)

**Comment by tmjo** [comment]
Found [this](https://developers.home-assistant.io/blog/2023/02/08/sensor_presentation_rounding/) and [this ](https://github.com/home-assistant/core/pull/87619). Seems like frontend stuff must do the rounding, or possible call some added features. I'll try to look into this soon.

**Comment by storebatfar** [comment]
I have the same issue after updating to latest version.

**Comment by AMajland** [comment]
I see the same behavior after upgrading to HA Core 2023.4.4 so yes it looks like a HA feature with front end configuration of precision.
![image](https://user-images.githubusercontent.com/97510471/232708034-dc5574da-73da-47bc-a006-5eaa25fd14ef.png)

**Comment by tmjo** [comment]
Should be fixed in v0.2.4. Applied a default one decimal digit for all entities, but it can be customized by adding round-parameter and the number of digits that is preferred.

**Comment by stefaanbolle** [comment]
When defining round: 0 I still get 1 digit after the comma. Is it possible to round and display to the closest integer without usin g commas?

**Comment by tmjo** [comment]
Really sorry for the delay, but this should be solved now in v0.2.7 released today.
